export const chartProps = {
  autosize: true,
  symbol: "BINANCE:BTCUSDT",
  interval: "15",
  timezone: "Etc/UTC",
  transparent: true,
  style: "1",
  locale: "uk",
  withdateranges: true,
  hide_side_toolbar: false,
  range: "1D",
  hotlist: true,
  details: true,
  enable_publishing: true,
  allow_symbol_change: true,
  container_id: "chart-container",
  watchlist: [
    "BINANCE:BTCUSDT",
    "BINANCE:ETHUSDT",
    "BINANCE:BNBUSDT",
    "BINANCE:ADAUSDT",
    "BINANCE:XRPUSDT",
    "BINANCE:DOGEUSDT",
    "BINANCE:DOTUSDT",
    "BINANCE:UNIUSDT",
    "BINANCE:SOLUSDT",
    "BINANCE:LINKUSDT",
    "BINANCE:LTCUSDT",
    "BINANCE:MATICUSDT",
  ],
}
