export const chartProps = {
  autosize: true,
  symbol: "BINANCE:BTCUSDT",
  interval: "D",
  timezone: "Etc/UTC",
  isTransparent: true,
  style: "1",
  locale: "uk",
  withdateranges: true,
  hide_side_toolbar: false,
  range: "3M",
  hotlist: true,
  details: true,
  enable_publishing: true,
  allow_symbol_change: true,
  container_id: "chart-container",
}
